### ISSUE TITLE
Rename the release branch to 'main'

### ISSUE THREAD

**Issue by parzhitsky** [parzh/xrange#177]
Scope of work:
- change GitHub workflows;
- change docs and READMEs;
- change branch protection rules;

Strategy (How to rename `master` to `main`):
- [x] create another pointer to `master`, called `main` (`git checkout master; git checkout -b main`);
- [x] sync it with the remote (`git push -u origin/main`);
- [x] setup the same branch protection rules for `main` as they are for `master`;
- [x] remove `master` branch entirely
- [x] make all the necessary changes, and put the commit in a feature branch;
- [x] make a PR from feature to `develop`, verify required unit tests are passing, merge it;
- [x] make a PR from `develop` to `main`, verify required GitHub Actions are passing;
- [x] merge PR, verify that a new version is being published;

**Comment by parzhitsky** [comment]
Set to `Pending: unclear` until the scope of work in the repository settings is clear

**Comment by parzhitsky** [comment]
Strategy (How to rename `master` to `main`):
- create another pointer to `master`, called `main` (`git checkout master; git checkout -b main`);
- sync it with the remote (`git push -u origin/main`);
- setup the same branch protection rules for `main` as they are for `master`;
- make all the necessary changes, and put the commit in a feature branch;
- make a PR from feature to `develop`, verify required unit tests are passing, merge it;
- make a PR from `develop` to `main`, verify required GitHub Actions are passing;
- merge PR, verify that a new version is being published;
